// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUmSVv17yb3kR_Sz3y4Gi1Jrrj5IzyPM',
    appId: '1:267493292267:web:ff94136fdc744b65f926ae',
    messagingSenderId: '267493292267',
    projectId: 'daily-expense-bc10f',
    authDomain: 'daily-expense-bc10f.firebaseapp.com',
    storageBucket: 'daily-expense-bc10f.firebasestorage.app',
    measurementId: 'G-KBWB7DCYS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtoV3nZsJF8CM3Lm46-iLW5sqm6qA5Su4',
    appId: '1:267493292267:android:4e39f7380e441f90f926ae',
    messagingSenderId: '267493292267',
    projectId: 'daily-expense-bc10f',
    storageBucket: 'daily-expense-bc10f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBeq9nL4MFRhUlBBy9YKI7B9cF8sz9x0',
    appId: '1:267493292267:ios:46bd943cb79f41bcf926ae',
    messagingSenderId: '267493292267',
    projectId: 'daily-expense-bc10f',
    storageBucket: 'daily-expense-bc10f.firebasestorage.app',
    iosBundleId: 'com.example.myDailyExpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBeq9nL4MFRhUlBBy9YKI7B9cF8sz9x0',
    appId: '1:267493292267:ios:46bd943cb79f41bcf926ae',
    messagingSenderId: '267493292267',
    projectId: 'daily-expense-bc10f',
    storageBucket: 'daily-expense-bc10f.firebasestorage.app',
    iosBundleId: 'com.example.myDailyExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdUmSVv17yb3kR_Sz3y4Gi1Jrrj5IzyPM',
    appId: '1:267493292267:web:fb978a240756cb5af926ae',
    messagingSenderId: '267493292267',
    projectId: 'daily-expense-bc10f',
    authDomain: 'daily-expense-bc10f.firebaseapp.com',
    storageBucket: 'daily-expense-bc10f.firebasestorage.app',
    measurementId: 'G-9E0XNPB04M',
  );
}
